parameters:
- name: OverrideBlockOnPossibleDataLoss
  displayName: Add /p:BlockOnPossibleDataLoss=false argument to DACPAC deployment
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: SolutionBaseName
  value: SFA.DAS.CompaniesHouse
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-companieshouse

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.26
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.5.10
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      SolutionBaseName: $(SolutionBaseName)
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss }}

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  variables:
  - group: Prod Management Resources
  - group: Prod Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PROD
      ServiceConnection: SFA-DIG-Prod-ARM
      SolutionBaseName: $(SolutionBaseName)
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss }}
    