parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: Version
  pool:
    name: DAS - Continuous Integration Agents
    workspace:
      clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-companieshouse

- template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
  parameters:
    SolutionBaseName: ${{ parameters.SolutionBaseName }}
    SqlProjectPath: src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.Database.sqlproj
