parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: Version
  pool:
    name: DAS - Continuous Integration Agents
    workspace:
      clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact ${{ parameters.SolutionBaseName }}
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
- template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
  parameters:
    SolutionBaseName: ${{ parameters.SolutionBaseName }}
    SqlProjectPath: src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.Database.sqlproj
