CREATE TABLE dbo.CompaniesHouseData
(
		CompanyName								Nvarchar(200), 
		CompanyNumber							Nvarchar(50),
		RegAddressAddressLine1					Nvarchar(200), 
		RegAddressAddressLine2					Nvarchar(200), 
		RegAddressPostTown						Nvarchar(100),
		RegAddressCounty						Nvarchar(50),
		RegAddressCountry						Nvarchar(50),
		RegAddressPostCode						Nvarchar(50),
		CompanyCategory							Nvarchar(100),
		CompanyStatus							Nvarchar(100),
		CountryOfOrigin							Nvarchar(50),
		DissolutionDate							Nvarchar(50),
		IncorporationDate						Nvarchar(50), 
		AccountsAccountRefDay					Nvarchar(50), 
		AccountsAccountRefMonth					Nvarchar(50),
		AccountsNextDueDate						Nvarchar(50),
		AccountsLastMadeUpDate					Nvarchar(50),
		AccountsAccountCategory					Nvarchar(200),
		ReturnsNextDueDate						Nvarchar(50), 
		ReturnsLastMadeUpDate					Nvarchar(50),
		MortgagesNumMortCharges					Nvarchar(100),
		MortgagesNumMortOutstanding				Nvarchar(100),
		MortgagesNumMortPartSatisfied			Nvarchar(100),
		MortgagesNumMortSatisfied				Nvarchar(100),
		SICCodeSicText_1						Nvarchar(250),
		SICCodeSicText_2						Nvarchar(250),
		SICCodeSicText_3						Nvarchar(250),
		SICCodeSicText_4						Nvarchar(250),
		NumGenPartners							Nvarchar(50),
		NumLimPartners							Nvarchar(50),
		URI										Nvarchar(200),
		PreviousNameCONDATE						Nvarchar(100),
		PreviousNameCompanyName					Nvarchar(200),
		ConfStmtNextDueDate						Nvarchar(50),
		ConfStmtLastMadeUpDate					Nvarchar(50)
)  