CREATE PROCEDURE [dbo].[ImportCompaniesHouseToPL]
(
   @RunId int
)
AS
-- ==========================================================================================================
-- Author:      Sarma Evani
-- Description: Import to [dbo].[CompaniesHouseData] PL table 
-- ==========================================================================================================
BEGIN TRY
		DECLARE @LogID int
		INSERT INTO [dbo].[CompaniesHouseData]
						   ([CompanyName]
						   ,[CompanyNumber]
						   ,[RegAddressAddressLine1]
						   ,[RegAddressAddressLine2]
						   ,[RegAddressPostTown]
						   ,[RegAddressCounty]
						   ,[RegAddressCountry]
						   ,[RegAddressPostCode]
						   ,[CompanyCategory]
						   ,[CompanyStatus]
						   ,[CountryOfOrigin]
						   ,[DissolutionDate]
						   ,[IncorporationDate]
						   ,[AccountsAccountRefDay]
						   ,[AccountsAccountRefMonth]
						   ,[AccountsNextDueDate]
						   ,[AccountsLastMadeUpDate]
						   ,[AccountsAccountCategory]
						   ,[ReturnsNextDueDate]
						   ,[ReturnsLastMadeUpDate]
						   ,[MortgagesNumMortCharges]
						   ,[MortgagesNumMortOutstanding]
						   ,[MortgagesNumMortPartSatisfied]
						   ,[MortgagesNumMortSatisfied]
						   ,[SICCodeSicText_1]
						   ,[SICCodeSicText_2]
						   ,[SICCodeSicText_3]
						   ,[SICCodeSicText_4]
						   ,[NumGenPartners]
						   ,[NumLimPartners]
						   ,[URI]
						   ,[PreviousNameCONDATE]
						   ,[PreviousNameCompanyName]
						   ,[ConfStmtNextDueDate]
						   ,[ConfStmtLastMadeUpDate])
				SELECT [CompanyName]
					  ,[CompanyNumber]
					  ,[RegAddressAddressLine1]
					  ,[RegAddressAddressLine2]
					  ,[RegAddressPostTown]
					  ,[RegAddressCounty]
					  ,[RegAddressCountry]
					  ,[RegAddressPostCode]
					  ,[CompanyCategory]
					  ,[CompanyStatus]
					  ,[CountryOfOrigin]
					  ,try_convert(date,[DissolutionDate],105) As [DissolutionDate]
					  ,try_convert(date,[IncorporationDate],105) As [IncorporationDate]
					  ,try_convert(smallint,[AccountsAccountRefDay]) As [AccountsAccountRefDay]
					  ,try_convert(smallint,[AccountsAccountRefMonth]) As [AccountsAccountRefMonth]
					  ,try_convert(date,[AccountsNextDueDate],105) As [AccountsNextDueDate]
					  ,try_convert(date,[AccountsLastMadeUpDate],105) As [AccountsLastMadeUpDate] 
					  ,[AccountsAccountCategory]
					  ,try_convert(date,[ReturnsNextDueDate],105) As [ReturnsNextDueDate]  
					  ,try_convert(date,[ReturnsLastMadeUpDate],105) As [ReturnsLastMadeUpDate]
					  ,try_convert(smallint,[MortgagesNumMortCharges]) As [MortgagesNumMortCharges]
					  ,try_convert(smallint,[MortgagesNumMortOutstanding]) As [MortgagesNumMortOutstanding]
					  ,try_convert(smallint,[MortgagesNumMortPartSatisfied]) As [MortgagesNumMortPartSatisfied]
					  ,try_convert(smallint,[MortgagesNumMortSatisfied]) As [MortgagesNumMortSatisfied]
					  ,[SICCodeSicText_1]
					  ,[SICCodeSicText_2]
					  ,[SICCodeSicText_3]
					  ,[SICCodeSicText_4]
					  ,try_convert(smallint,[NumGenPartners]) As [NumGenPartners]
					  ,try_convert(smallint,[NumLimPartners]) As [NumLimPartners]
					  ,[URI]
					  ,try_convert(date,[PreviousNameCONDATE],105) As [PreviousNameCONDATE]
					  ,[PreviousNameCompanyName]
					  ,try_convert(date,[ConfStmtNextDueDate],105) As [ConfStmtNextDueDate]
					  ,try_convert(date,[ConfStmtLastMadeUpDate],105) As [ConfStmtLastMadeUpDate]					  
				  FROM [dbo].[CompaniesHouseData]
				 				  
END TRY
BEGIN CATCH
	
END CATCH